### ISSUE TITLE
give todo comments a different color than standard comments

### ISSUE THREAD

**Issue by hab25** [qyurila/ayu-dark-jetbrains#1]
The default (darcula) color scheme has this:
![image](https://user-images.githubusercontent.com/31970961/189467008-21200992-d78a-4ea9-a94e-75f1180831bc.png)

[ayu-dark-jetbrains](https://github.com/qyurila/ayu-dark-jetbrains) does not:
![image](https://user-images.githubusercontent.com/31970961/189467015-3e2a6689-f93b-4a06-8bde-c52ee7ca5992.png)

It's useful: todo comments are typically more important and rarer than regular ones. 

The parsing and identifying of todo comments is by something else in the IDE, and  the user can toggle it on/off outside of color scheme settings, so [ayu-dark-jetbrains](https://github.com/qyurila/ayu-dark-jetbrains) does not need to worry about this.

**Comment by qyurila** [comment]
Thank you for creating the issue! The improvement will be shipped with v1.1.0.
